### ISSUE TITLE
Publish to Store

### ISSUE THREAD

**Issue by Padamdam** [langerdennis/raycast-paperless#2]
Hi Dennis,

I would love for the extension to be available for everyone.

According to Raycast documentation, it is recommended that you proceed with the publish, since your repo is the source.

https://developers.raycast.com/basics/publish-an-extension#publish-your-extension

Would you care to proceed with the publication ?

Regards,
Adam

**Comment by langerdennis** [comment]
Hi Adam,

thank you for your suggestion! To be honest I had just quickly hacked this together and am not using my Mac as my main machine anymore, so I don't want to go through all the steps to prepare for publication (Screenshots, Changelog etc.). Should not be too much effort, but I am not planning to maintain the extension afterwards. I have no problem with you going ahead and publishing from a cloned repo in your own account however! The majority of features is coming from your PR anyways :)

Regards,
Dennis

**Comment by Padamdam** [comment]
Hey Dennis !

I went through the validation process, just wanted you to know that the extension has been published to the store.

Thanks for your work on the extension !

https://www.raycast.com/damdam/paperless-ngx

**Comment by langerdennis** [comment]
Hi Adam,
thank you so much for all the effort! Really to cool to see it official now :-)
Cheers!
